#!/bin/bash

#SBATCH --nodes=1
#SBATCH --tasks-per-node=3
#SBATCH --mem=500
#SBATCH --time=10
#SBATCH --partition=general
#SBATCH --job-name=Fastqc_Analysis1

set -eu

source new-modules.sh; module load fastqc/0.11.2-fasrc01 
fastqc \
  --outdir /n/informatics/IggyTools/iggytools/iggypipeline/test/Fastqc \
  --threads 4 \
  --noextract \
  --nogroup \
  /n/informatics/IggyTools/iggytools/iggypipeline/test/samp1.fastq

#This script was generated by iggypipe
