#!/bin/bash

#SBATCH --nodes=1
#SBATCH --tasks-per-node=16
#SBATCH --mem=16000
#SBATCH --time=48:00
#SBATCH --partition=general
#SBATCH --job-name=Bowtie2_Analysis1

set -eu

source new-modules.sh; module load bowtie2/2.2.2-fasrc01; cd /n/informatics/IggyTools/iggytools/iggypipeline/test/Bowtie2 
bowtie2 -q --time \
  --phred33 \
  -x /n/regal/informatics_public/ref/ensembl/release-79/homo_sapiens/Homo_sapiens.GRCh38.cds.all \
  -U /n/informatics/IggyTools/iggytools/iggypipeline/test/samp1.fastq \
  -S /n/informatics/IggyTools/iggytools/iggypipeline/test/Bowtie2/alignment_bt2.sam \
  --threads 16 \
  --met-file /n/informatics/IggyTools/iggytools/iggypipeline/test/Bowtie2/metrics_bt2.txt \


#This script was generated by iggypipe
